### ISSUE TITLE
Empty ZIP files generated - why?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PyFilesystem/pyfilesystem#183]
```
The following code is supposed to generate a ZIP file with one file foo.txt 
inside. However the resulting out.zip file is empty. Why?
-----------

[ajung@dev1 onkopedia_buildout]$ cat x.py 
import fs.zipfs


z = fs.zipfs.ZipFS('out.zip', 'w')
z.open('foo.txt', 'wb').write('nmj')
z.close()


[ajung@dev1 onkopedia_buildout]$ bin/zopepy x.py 
[ajung@dev1 onkopedia_buildout]$ !un
unzip out.zip 
Archive:  out.zip
warning [out.zip]:  zipfile is empty

```

Original issue reported on code.google.com by `zopyxfilter` on 31 Jul 2014 at 6:17

**Comment by ThiefMaster** [comment]
Shouldn't whatever is returned by `z.open()` have a `__del__` method that closes it automatically? At least that's the behavior of other file-like objects in Python (of course `open('foo', 'w').write('bar')` is still ugly, but people do it nonetheless ;x)

**Comment by willmcgugan** [comment]
It does, but in the original code the file didn't go out of scope. It was still open at the time the zipfs was closed.
