### ISSUE TITLE
AWS Credentials for S3 shouldn't require environment variables

### ISSUE THREAD

**Issue by notpeter** [PyFilesystem/pyfilesystem#211]
Boto supports multiple ways to provide AWS credentials (key and key_id) besides just as environment variables.  More info in [the boto docs](http://boto.readthedocs.org/en/latest/boto_config_tut.html#details).

But basically instead of requiring environment variables [see fs/s3fs.py] (https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/s3fs.py#L112) we can let boto pull it from the ~/.aws/credentials file (supported by boto, boto3 and other AWS SDKs) or other standardized locations as well as from IAM roles (using ec2 instance metadata magic) when running on EC2 without having to hard-code credentials.

**Comment by zopyx** [comment]
+1

**Comment by jimbocoder** [comment]
+1

**Comment by hevy-CC4477** [comment]
+1
I am currently using fs==0.5.4. And I need to export my AWS env variable, fs does not seems to find ~/.aws/credentials.

Here is how I am using fs right now:
```
store = fsopendir('s3://' + bucket_name)
store.exists(key)
```
