### ISSUE TITLE
OSFS.unsyspath on paths 6 chars long

### ISSUE THREAD

**Issue by potrebic** [PyFilesystem/pyfilesystem#219]
OSFS.unsyspath seems to special case paths that are 6 chars long (some Windows thing?), But that logic seems to mess up paths on Macs. For example:

> from fs.OSFS import OSFS
> fs = OSFS('/')
> fs.unsyspath(fs.getsyspath('abcde'))
u'abcde\\'

The original 'abcde' was corrupted to 'abcde\\'

**Comment by willmcgugan** [comment]
I think I can fix that by checking for the platform.

**Comment by willmcgugan** [comment]
pushed a quick fix
