### ISSUE TITLE
DropBox support

### ISSUE THREAD

**Issue by hmeine** [PyFilesystem/pyfilesystem#222]
It would be nice to see DropBox support as well.

**Comment by arekbulski** [comment]
Can you point to some open implemenation that allows access into Dropbox hosted files?

**Comment by hmeine** [comment]
We used this one: https://pypi.python.org/pypi/dropbox
Apparently, one would need to register a "pyfilesystem" application first, in order to get an API key.

**Comment by hmeine** [comment]
(With "we used", I meant in https://github.com/comic/comic-django, not with pyfilesystem yet.)

**Comment by travcunn** [comment]
Dropbox for pyfilesystem: https://github.com/smartfile/fs-dropbox

**Comment by hmeine** [comment]
Thanks, interesting.  I thought that caching would make more sense as a wrapper (I see you already commented on issue #223 ), but maybe there are aspects to caching that suggest a closer integration into remote filesystems.

**Comment by travcunn** [comment]
A few months back, I built a caching wrapper for a remote filesystem. One method that was cached was `exists()`, which would be invalidated after 1 second. This way, if `exists()` is called a bunch within the same second, it ask the remote server again.

**Comment by hmeine** [comment]
Exactly, and the remote fs might even provide some change notification / timestamping / bulk-stat() / similar API.  But this is actually guessing, I have no real FS in mind.

**Comment by hmeine** [comment]
Will dropbox support be merged eventually, and this issue stays open until it is?

**Comment by arekbulski** [comment]
If that is developed outside of this project then close it.

**Comment by xmedeko** [comment]
I vote for merging the @travcunn project into PyFilesystem, or please update the doc to include links to the external FS implementaions.

**Comment by jirikuncar** [comment]
We have tried to submit https://github.com/inveniosoftware-attic/invenio-ext/blob/master/invenio_ext/fs/cloudfs/dropboxfs.py to upstream years back.

**Comment by willmcgugan** [comment]
At some point I will collate these implementations on the website. Dropbox support is fantastic, but I'm trying to make PyFilesystem leaner in terms of dependancies.
