### ISSUE TITLE
"Automatically exported from code.google.com/p/pyfilesystem" really important today?

### ISSUE THREAD

**Issue by guettli** [PyFilesystem/pyfilesystem#226]
On top of this projects page to github:

> Automatically exported from code.google.com/p/pyfilesystem

Is this really that important today?

**Comment by arekbulski** [comment]
I suggest the repository title be changed to (will only take a minute)

**Python abstraction layer for filesystems**

and we can close the issue.

**Comment by aisch** [comment]
:+1: or `Python ` + whatever is setup.py desc https://github.com/PyFilesystem/pyfilesystem/blob/master/setup.py#L47.

**Comment by lurch** [comment]
Done :-)
