### ISSUE TITLE
Interface for hardlink/symlink?

### ISSUE THREAD

**Issue by arekbulski** [PyFilesystem/pyfilesystem#228]
I noticed there is no interface for managing hardlinks and symbolic links. This might be a hard requirement for me. I need to implement a real on-disk filesystem and I would prefer to implement it in pyfilesystem and expose it through FUSE, rather than implement in FUSE and mount here. 

Would it be acceptable for me to draft an extension to the base class, with NotSupported default implementation, and FUSE exposing class to make use of it? 

If the owner gives a green light, I promise to implement it 100% and test it throughly.

@willmcgugan Please give a go?

**Comment by lurch** [comment]
See also #79 for an example of where this was discussed previously

**Comment by arekbulski** [comment]
Good reference. So this was already debated at least since April...

**Comment by lurch** [comment]
Nope, it was imported from GoogleCode to GitHub in April ;-)  The bit you want to look at is `Original issue reported on code.google.com by ha...@midnight-labs.org on 20 Jul 2011 at 12:17` - i.e. over 4 years ago!

I wasn't suggesting that this issue should be closed, more that it's also something else that people have asked for... but I guess there's no reason you can't add your comments to #79 instead.

**Comment by arekbulski** [comment]
I dont think this will be ever even considered by the owner. Thats why I closed it.
