### ISSUE TITLE
Difference between move() and rename()

### ISSUE THREAD

**Issue by arekbulski** [PyFilesystem/pyfilesystem#230]
What is the difference? Is it just that rename has the destination path truncated to just the final component?

~~Does base class FS implement by default one by means of another?~~

Could anyone explain to me the semantics?

**Comment by arekbulski** [comment]
It is kinda sad that no one cared to even respond to this question since December. This is a basic question that should be clear after just looking at docstrings. Now I understand why I found opinions that this project is no longer maintained.

**Comment by lurch** [comment]
I personally try to help out on pyfilesystem here and there, but there are other open-source [projects](https://github.com/RPi-Distro/python-gpiozero) which have more of my attention currently.
And it seems like the original project author @willmcgugan (who is obviously the person best placed to answer your original question) also has his focus [elsewhere](https://github.com/moyaproject) recently...

That doesn't mean that this project has been abandoned.

**Comment by pyhedgehog** [comment]
By definition this exactly means that project is [abandoned](https://en.wiktionary.org/wiki/abandoned):
"2. No longer maintained by its former owners, residents, or caretakers."

**Comment by willmcgugan** [comment]
It's not abandoned.

To answer @arekbulski's original question, `rename` is atomic, where `move` may do a read / write / delete operation. You should generally use `move`, unless you require it to be atomic.

GitHub issues aren't the best place for questions. http://groups.google.com/group/pyfilesystem-discussion is better for that.

**Comment by arekbulski** [comment]
Thank you @willmcgugan ! I will put that into respective docstrings and and submit a pull request, so this issue wont come up again.

**Comment by lurch** [comment]
Note also the `atomic.rename` meta-value http://docs.pyfilesystem.org/en/latest/base.html#fs.base.FS.getmeta
