### ISSUE TITLE
Google drive support

### ISSUE THREAD

**Issue by linshu** [PyFilesystem/pyfilesystem#247]
Is there any plan to support google drive?

**Comment by lurch** [comment]
Not until somebody volunteers to write the code to do so...

**Comment by Ryanb58** [comment]
This would kind of be a nightmare since google does stuff based off ID's and allows for duplicates, whereas pytfilesystem does it's actions based off paths.

**Comment by jirikuncar** [comment]
There is a Google Drive plugin developed years back but never accepted to upstream.

https://github.com/inveniosoftware-attic/invenio-cloudconnector/blob/master/invenio_cloudconnector/fsopeners/google_drive.py

**Comment by Ryanb58** [comment]
@jirikuncar How does it mitigate the duplicate file name issue?

**Comment by jirikuncar** [comment]
> How does it mitigate the duplicate file name issue?

@Ryanb58 I think it doesn't correctly. We would need to extend the virtual tree map to support multiple items under same name. I am not sure how would it work with FUSE though. It was sufficient for our use-case, because we used it for application-managed-folder only.

**Comment by willmcgugan** [comment]
Google drive is a great use case, but fs2.0 is intended to have fewer dependancies. Things like GDrive will live as separate projects.
