### ISSUE TITLE
Python 3.5.1 64 bit windows import error?

### ISSUE THREAD

**Issue by apiszcz** [PyFilesystem/pyfilesystem#248]
>>> from fs.osfs import OSFS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib\fs\__init__.py", line 22, in <module>
    from fs import errors
  File "lib\fs\errors.py", line 220
    except ResourceNotFoundError, e:

**Comment by lurch** [comment]
How did you install it? http://docs.pyfilesystem.org/en/latest/getting_started.html

**Comment by apiszcz** [comment]
placed the fs folder in a 'lib' folder
sys.path.append('lib')
from fs.osfs import OSFS

**Comment by lurch** [comment]
That won't work - the installation (whether `pip` or `setup.py` needs to run 2to3 in order to convert the code to be Python3-compatible.

**Comment by apiszcz** [comment]
Thank you for creating the fs, that is the piece of information needed, all
set.

lib\python\python
>>> import sys
>>> sys.path.append('lib')
>>> from fs.osfs import OSFS
>>> home_fs = OSFS('~/')
>>> dir(home_fs)
['_OSFSWatchMixin__get_watch_thread',
'_OSFSWatchMixin__shutdown_watch_thread', '_OSFSWatchMixin__watch_lock',
'_OSFSWatchMixin__watch_thread', '__class__', '__del__', '__delattr__',
'__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__',
'__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__',
'__hash__', '__init__', '__iter__', '__le__', '__lt__', '__module__',
'__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__',
'__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__',
'__unicode__', '__weakref__', '_decode_path', '_find_watchers',
'_listdir_helper', '_lock', '_meta', '_re_invalid_chars', '_setcontents',
'_shutil_copyfile', '_shutil_movefile', '_stat', '_watchers',
'add_watcher', 'browse', 'cache_hint', 'cachehint', 'close', 'closed',
'copy', 'copydir', 'createfile', 'del_watcher', 'delxattr', 'desc',
'dir_mode', 'encoding', 'exists', 'getcontents', 'getinfo', 'getinfokeys',
'getmeta', 'getmmap', 'getpathurl', 'getsize', 'getsyspath', 'getxattr',
'hasmeta', 'haspathurl', 'hassyspath', 'ilistdir', 'ilistdirinfo', 'isdir',
'isdirempty', 'isfile', 'isvalidpath', 'listdir', 'listdirinfo',
'listxattrs', 'makedir', 'makeopendir', 'move', 'movedir',
'notify_watchers', 'open', 'opendir', 'printtree', 'remove', 'removedir',
'rename', 'root_path', 'safeopen', 'setcontents', 'setcontents_async',
'settimes', 'setxattr', 'thread_synchronize', 'tree', 'unsyspath',
'use_long_paths', 'validatepath', 'walk', 'walkdirs', 'walkfiles']

**Comment by lurch** [comment]
Glad you managed to get it working :)
