### ISSUE TITLE
We need a commiter, I volunteer

### ISSUE THREAD

**Issue by arekbulski** [PyFilesystem/pyfilesystem#259]
There are too many pull requests just hanging dry. We need someone with priviliges to start working on the backlog. I volunteer myself, would you allow me in the main repository? I became familiar with the base class and dokany exposing class (https://github.com/PyFilesystem/pyfilesystem/pull/258).

Ping @lurch @willmcgugan .

**Comment by arekbulski** [comment]
I would like to start fixing bugs in expose/fuse/ but there wilk be no one to accept my patches in main repository. We definiely need an Active maintainer.

**Comment by lurch** [comment]
I realise you're eager to help, but as the old saying goes "patience is a virtue" ;-)

@willmcgugan is the project owner, so it'd be up to him to add you as a new maintainer, but IMHO project contributors really need to spend quite some time working with a codebase (just as I did before @willmcgugan gave me commit access) before they get given write-access. Stick around long enough, and that may happen :)
Feel free to test and/or add comments on some of the existing PRs and issues if you want to help.

**Comment by willmcgugan** [comment]
I certainly appreciate your efforts, @arekbulski! I haven't had much time to work on Pyfilesystem, but I promise I'll go through the PRs within the next few weeks. :)

**Comment by arekbulski** [comment]
Fine! I will proceed with reviewing and fixing.

**Comment by arekbulski** [comment]
@lurch Sorry if I am making too much hastle with all the "maybe close this or this or this...". Just trying to find some stuff that can be easily checked out, before more laborous things. If you want me to flag less just say a word.

**Comment by lurch** [comment]
No, it's all helpful :-)
If nothing else, reviewing all the issues gives you an idea of the areas of pyfilesystem that people want more work done on.

**Comment by arekbulski** [comment]
Yes, I am seriously considering implementing CacheFS just so I can close the damn issue. 😀

**Comment by lurch** [comment]
Hopefully you're not so pessimistic about the state of this project now? ;-)

**Comment by arekbulski** [comment]
Nope, I see now that there is more work to do than hands on.
