### ISSUE TITLE
Fuse module: much cleanup is needed

### ISSUE THREAD

**Issue by arekbulski** [PyFilesystem/pyfilesystem#261]
I found something strange, `expose/fuse/__init__.py` imports one of two modules, but the `fuse.py` is NEVER loaded by either three remaining files. Could someone confirm I am not imagining things? Also file names seem to be wrong, `fuse3` is loaded only on PY 2.
https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/expose/fuse/__init__.py#L73

**Comment by lurch** [comment]
That's quite possible. The FUSE stuff all looks quite confusing, and years ago there was lots of discussion around macfuse, fusepy, osxfuse, fuse4x, fuse-python, etc. etc.
So I've personally been deliberately avoiding touching the FUSE code with a bargepole ;-)

It would be great if someone who knows what's what is able to sort it all out!

**Comment by anastmag** [comment]
Hi @lurch 
Let me investigate it as my first contribution to the project.
Best
Anastasios

**Comment by arekbulski** [comment]
@anastmag Great, we need more hands on.

**Comment by anastmag** [comment]
Why have you decided to implement your own custom fuse bindings and not relied to pyfuse ?

**Comment by arekbulski** [comment]
I didnt implement anythting if you were replying to me. It is generalny better to have own copy of a module than merely reference it. Pyfuse can get broken or removed, we wont be affected.

**Comment by arekbulski** [comment]
Until fuse binaries change, which is unlikely, that is.

**Comment by anastmag** [comment]
Thanks for the reply. You were pretty much informative.

**Comment by lurch** [comment]
> Why have you decided to implement your own custom fuse bindings and not relied to pyfuse ?

A lot of the code in pyfilesystem is getting quite old now, so the original reasons some of the features were implemented the way they were, may be lost in the mists of time?

@willmcgugan and @rfk wrote a lot of the original code... so maybe they might have some helpful comments... ;-)

**Comment by arekbulski** [comment]
The code was imported. See
https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/expose/fuse/__init__.py

**Comment by JokerQyou** [comment]
Fuse4x is dead as far as I know. [Osxfuse](https://github.com/osxfuse/osxfuse) is the de facto FUSE framework for OS X now, and pyfilesystem does not support it currently. I think #170 and #151 might be useful references for OS X platform if someone is going to refactor the FUSE module.
