### ISSUE TITLE
SFTPFS fails to connect.

### ISSUE THREAD

**Issue by chibill** [PyFilesystem/pyfilesystem#264]
Trying to connect to my server and use a SFTPFS always ends in a 
`paramiko.SSHException: Unable to connect to 192.178.1.83: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

I know that the ip is correct because I can connect to it with any other ssh client including paramiko.

Code used. 
t =SFTPFS(("192.178.1.83",22),username="******_",password="**_*****",agent_auth=False,hostkey=None)

Background. Windows 10, Python 2.7.12 connecting to Debain Jessie remote host

**Comment by chibill** [comment]
Okay this is strange.... It works from my external ip but will not work thru my local lan.

**Comment by willmcgugan** [comment]
Did you manage to figure out what caused that at all?

**Comment by chibill** [comment]
nope. Still can't get it to work locally. Not sure why. Going to try again now.

**Comment by chibill** [comment]
Well it works now for some reason.. Not sure why it was not before.

**Comment by willmcgugan** [comment]
Temporary network issue maybe. Thanks for checking.

**Comment by chibill** [comment]
I was strange as I was sitting next to the physical machine. (Which is hardwired to my router)
