### ISSUE TITLE
Segmentation fault: 11 with SFTP

### ISSUE THREAD

**Issue by chris-hailstorm** [PyFilesystem/pyfilesystem#265]
Trying a fairly vanilla command line:

```
$ fsls sftp://name:passwowrd@sftp.whatever.com
Segmentation fault: 11
```

Has anyone else seen this?  I'm using Python 2.7.12 on OSX 10.9.5

This kind of error is not unheard of with Paramiko and / or the cryptography module but can be pretty hard to resolve.  I'm hoping someone else has seen this before.

**Comment by chris-hailstorm** [comment]
Resolved by reinstalling cryptography in a non-obvious way:

```
    pip uninstall cryptography
    LDFLAGS="-L/usr/local/opt/openssl/lib" pip install cryptography --no-use-wheel
```

See [](http://stackoverflow.com/a/34132165/763269)

**Comment by lurch** [comment]
Glad to hear you managed to solve your problem. As this isn't directly related to pyfilesystem, can this issue be closed?
