### ISSUE TITLE
How do we install this version from pip?

### ISSUE THREAD

**Issue by chibill** [PyFilesystem/pyfilesystem#272]
As the command noted to install this version is the same as for the pyfilesystem2 version.. Which is missing key things I need... (Like for example actually being able to use the filesystem out side of python... A key feature that has not been touched at all in pyfilesystem2..... )

Why a core feature was forgotten in pyfilesystem2 I don't know... Its claimed that it will have its own package but no work as been done on it at all.

**Comment by willmcgugan** [comment]
`pip install fs==0.5.4` will get you the most recent stable version of fs1.

**Comment by chibill** [comment]
Okay. Why has expose then throw away in pyfilesystem2? Just asking...

**Comment by willmcgugan** [comment]
The FS2 package is intended to require minimal dependancies so that can be installed anywhere, which means it has to focus on the core functionality.

Fuse and Doken are quite dependancy heavy, and OS dependant which makes them tricky to package. They are also a lot of work to maintain. If they are ported, it will be as separate package(s).

**Comment by chibill** [comment]
So basically there won't be expose for pyfs2 unless we figure it out? 

And expose was one the things holding me back from pyfs2 as I  want to actually be able to use the filesystems I create with out having to read the file then write it to my local disk.

**Comment by chibill** [comment]
It actually does not look that bad to port as long as pyfilesystem2 did not mess up basic stuff..

**Comment by chibill** [comment]
Also that means expose is no longer a part of pyFS2 core functionality?

**Comment by willmcgugan** [comment]
Expose was never really core functionality. It would be nice to have, but it's not currently a priority.

Bear in mind, you get this code for free, and open source developers owe you nothing. Bad mouthing projects on Twitter is not the way to go about seeking help.

**Comment by chibill** [comment]
I have not bad mouth any thing yet. Pointing stuff out yes bad mouthing no.
