### ISSUE TITLE
Why does the size of mounted disk always fixed?

### ISSUE THREAD

**Issue by Pagliacii** [PyFilesystem/pyfilesystem#276]
@Liryna 
Why does the size of mounted disk always like 100GB/200GB?
How could I change the size?
```python
>>> from fs.memoryfs import MemoryFS
>>> from fs.expose import dokan
>>> memfs = MemoryFS()
>>> dokan.mount(memfs, "Z:\\")
<fs.expose.dokan.MountProcess object at 0x0000000006A82FD0>
```
![image](https://user-images.githubusercontent.com/12871143/32087465-7ea3e720-bb0e-11e7-8b72-44d50759fc2a.png)

**Comment by Liryna** [comment]
@Pagliacii this is handle by GetDiskFreeSpace. Seems like it use the free_space total_space meta data.
https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/expose/dokan/__init__.py#L743-L751

**Comment by Pagliacii** [comment]
@Liryna It doesn't work.
![image](https://user-images.githubusercontent.com/12871143/32131257-4cfa7670-bbdc-11e7-97d2-560ccc87114b.png)
![image](https://user-images.githubusercontent.com/12871143/32131269-80b21414-bbdc-11e7-923f-c3354358033d.png)

**Comment by Liryna** [comment]
can you add logs in GetDiskFreeSpace to see if it is called and set the correct values ?

**Comment by Pagliacii** [comment]
Well, when I set the `foreground` to True, its size was changed. Thanks for your help, @Liryna :smile:

![image](https://user-images.githubusercontent.com/12871143/32132479-225ea1dc-bbf7-11e7-8058-f57a30855926.png)
![image](https://user-images.githubusercontent.com/12871143/32132506-9678ba08-bbf7-11e7-8b31-9720f4c55c87.png)

**Comment by Liryna** [comment]
@Pagliacii this is strange you need to set this variable 😮 
Probably the options are not correctly forward when the option is not enabled https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/expose/dokan/__init__.py#L1017
