### ISSUE TITLE
No module expose in last versions ?

### ISSUE THREAD

**Issue by buxx** [PyFilesystem/pyfilesystem#277]
Hello,
Documentation talk about `expose` module: http://pyfilesystem.readthedocs.io/en/latest/expose/index.html
But i can't found it in 2.x versions of pypi packages, ex https://pypi.python.org/packages/3f/5a/70e9b5e9873c9c986ce687f5ab334dc6e7c960899140e3ef641a04aa6551/fs-2.0.17.tar.gz#md5=aa9431768ec3fb01fab497ae16b6077c .

I can found it in previous versions. What it means ? I'm trying to mount webdav as network driver with dokan.

**Comment by willmcgugan** [comment]
There is no expose module in PyFilesystem2 as of yet. There is a project in progress to implement expose functionality an external module. 

PyFilesystem2 docs are [here](https://docs.pyfilesystem.org/en/latest/)

**Comment by buxx** [comment]
Okay, sorry for my error : ) Thx
